### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Frederick888** [Frederick888/git-credential-keepassxc#1]
Tasks to tackle:

- [x] Socket path

https://github.com/Frederick888/git-credential-keepassxc/blob/e77960b99633900d917a501472f5e0efe443609e/src/utils.rs#L29-L40

XDG probably doesn't work under Win. KeePassXC uses named pipes under Win and the path is `%TMP%\kpxc_server` (e.g. `C:\Users\Administrator\AppData\Local\Temp\kpxc_server`). It listens on another one called `keepassxc-Administrator.socket` at the same time, not sure whether it's for browser integration as well or not.

- [x] UnixStream -> Named pipe

https://github.com/Frederick888/git-credential-keepassxc/blob/e77960b99633900d917a501472f5e0efe443609e/src/utils.rs#L63-L72

Two most popular implementations are:
https://crates.io/crates/named_pipe
https://crates.io/crates/mio-named-pipes

We should probably use the first one as it doesn't seem to require a runtime. It's a synchronous CLI tool at the end of the day and we don't need asynchronous stuff.

https://github.com/Frederick888/git-credential-keepassxc/blob/e77960b99633900d917a501472f5e0efe443609e/src/utils.rs#L74-L91

`exchange_message()` needs to be updated as well.

- [x] Logger

https://github.com/Frederick888/git-credential-keepassxc/blob/e77960b99633900d917a501472f5e0efe443609e/src/main.rs#L465

Does [TermDecorator](https://docs.rs/slog-term/2.5.0/slog_term/struct.TermDecorator.html) work in cmd/PowerShell? Do we need to switch to [PlainSyncDecorator](https://docs.rs/slog-term/2.5.0/slog_term/struct.PlainSyncDecorator.html) under Win?

**Comment by Frederick888** [comment]
Might be useful: https://crates.io/crates/directories-next

**Comment by Frederick888** [comment]
@riedel Could you please give `1-windows-support` branch a shot?

I cross-compiled to `x86_64-pc-windows-gnu` using MinGW and I was able to use the program in Cygwin, e.g.
```sh
$ git-credential-keepassxc configure
$ git config --global credential.helper keepassxc
$ printf "url=https://example.com\nusername=foo\n" | git credential fill
```

In CMD/PowerShell the coloured output also looked ok but I don't know how to do I/O redirection in CMD/PowerShell so I didn't test credential retrieval.

And if everything on `1-windows-support` looks alright (fingers crossed lol!), is it also possible for you to try targeting `x86_64-pc-windows-msvc` then test it again? Thanks.

**Comment by riedel** [comment]
Cool it works!!!! Thanks!

However, I had a problem with multiple accounts. I guess I can open a ticket.

**Comment by Frederick888** [comment]
@riedel Thanks for testing msvc.

> However, I had a problem with multiple accounts. I guess I can open a ticket.

Because currently usernames are not used when retrieving credentials I guess. Anyway, please open another ticket for this and some debug (`-vvv`) logs would be appreciated.
