### ISSUE TITLE
Readme wrong in Configuration section

### ISSUE THREAD

**Issue by ephraim** [Frederick888/git-credential-keepassxc#102]
https://github.com/Frederick888/git-credential-keepassxc/blob/a05ac02b5c13026381c2cc63a540a3a6a4a9c48d/README.md?plain=1#L57

the  credential helper is not keepassxc but git-credential-keepassxc this was very confusing.

Cheers
Thilo

**Comment by Frederick888** [comment]
Look, I'm not asking too much, but can we at least give it a shot before filling an issue? https://github.com/Frederick888/git-credential-keepassxc/discussions/100

(And what's the deal with ignoring the whole issue template?)
