### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by ieugen** [Frederick888/git-credential-keepassxc#12]
Hello,

I've tried to build on Debian and it fails: 

I've run `cargo install git-credential-keepassxc` . 
I installed rust from repos.

```
cargo --version 
cargo 1.42.1

rustc --version
rustc 1.42.0

```

```
  Compiling prctl v1.0.0
   Compiling aes-gcm v0.6.0
error: attributes are not yet allowed on `if` expressions
  --> /home/ieugen/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.14.13/src/utils.rs:27:5
   |
27 |     #[allow(clippy::identity_conversion)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `sysinfo`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `git-credential-keepassxc v0.3.2`, intermediate artifacts can be found at `/tmp/cargo-installRE8O9G`

Caused by:
  build failed
```

**Comment by Frederick888** [comment]
This feature used by [`sysinfo`](https://crates.io/crates/sysinfo) is available from Rust 1.43.0 rust-lang/rust#69201

It's generally a good idea to keep Rust up-to-date.

**Comment by ieugen** [comment]
Thank you for the information.
I don't work with rust every day so I don't feel the need to do that.
I'm sure there are plenty more people like me. 
I'm not going to jump through hoops to use this app. 
Thanks.

**Comment by Frederick888** [comment]
@ieugen Well, you can then report this issue to `sysinfo` although I don't think they'd hold back from using new Rust features. At the end of the day it's not something I can fix here.

**Comment by Frederick888** [comment]
Just wanna drop a note that now I use GitHub Actions to build and upload binaries to the [release page](/Frederick888/git-credential-keepassxc/releases). This is experimental though, it's still suggested to use `cargo` to install this tool.
