### ISSUE TITLE
OS Error 2 file not found

### ISSUE THREAD

**Issue by bendem** [Frederick888/git-credential-keepassxc#13]
I'm getting this error when running on windows :
```
bendem> git-credential-keepassxc.exe -vvv configure
Jul 15 14:17:58.975 DEBG Subcommand: configure
Jul 15 14:17:58.979 INFO Sending change-public-keys request
Jul 15 14:17:58.981 DEBG SEND: {"action":"change-public-keys","publicKey":"b8RXkakSQFY+MNJGn1xhSnmPKMm65+2m1Jy82b81CyM=","nonce":"SYvqO+ttgrJH9OjMqc9KO1z55/CDw4lc","clientID":"7sG9XEgiZEUhzvoXJLcchKS8W6QJa1to"}
Jul 15 14:17:58.982 DEBG Socket path: \\.\pipe\\C:\Users\bendem\AppData\Local\Temp\org.keepassxc.KeePassXC.BrowserServer
Jul 15 14:17:58.984 ERRO Le fichier spécifié est introuvable. (os error 2), Caused by: N/A, Message: Le fichier spécifié est introuvable. (os error 2)
[105.01 ms]
```

I'm guessing the problem comes from using the OS temp dir while windows pipes are (from what I understand) in `\\.\pipe\`.

Ref https://github.com/keepassxreboot/keepassxc/issues/5069

**Comment by Frederick888** [comment]
Could you please share the actual full path of your KPXC pipe? I seldom use Windows but IIRC the last time I tested it out and this path worked just alright.

**Comment by bendem** [comment]
It's one of those two, no idea which one:

```
\\.\pipe\keepassxc-DEMARTEAUB.socket
\\.\pipe\org.keepassxc.KeePassXC.BrowserServer
```

**Comment by Frederick888** [comment]
Ah, I get it.

It's the second one. But apparently under Windows since KPXC 2.6.0, not only has the name of the pipe been changed, but also the path. It used to be the one in the log that's relative to user's `FOLDERID_LocalAppData`. (I wonder what happens now when multiple users share the same machine though.)

It should be a minor fix but I haven't got the time to do it atm. You can try `--socket` for now.

**Comment by bendem** [comment]
My guess is that `\\.\pipe\` is somehow a user path, not sure exactly what it is hiding.

`--socket` works for `configure`, but `get` shows the original error message (file not found) with no more information when passing `-vvv`.

```
bendem> 'https://example.org' | git-credential-keepassxc.exe -vvv --socket '\\.\pipe\org.keepassxc.KeePassXC.BrowserServer' get
Jul 15 15:24:03.439 DEBG Subcommand: get
Jul 15 15:24:03.447 ERRO Le fichier spécifié est introuvable. (os error 2), Caused by: N/A, Message: Le fichier spécifié est introuvable. (os error 2)
[117.94 ms]
```

**Comment by Frederick888** [comment]
Welp, guess we've got two bugs then lol. I'll see if I can have some time to figure it out tomorrow or the day after.

**Comment by bendem** [comment]
No rush, thanks for taking the time to look into it!

**Comment by Frederick888** [comment]
Actually I suspect that the `get` problem is related to configuration file rather than socket/pipe (gosh I need to improve logging). The default configuration path should be `{FOLDERID_RoamingAppData}\git-credential-keepassxc` under Windows. Can you confirm whether this file exists, and in case you are using something like Cygwin/MSYS/PowerShell/etc, can you also just try cmd instead?

Btw if configuration file path is indeed the reason you can manually specify the path using `--config`.

**Comment by bendem** [comment]
I'm testing each time with cmd, powershell and wsl's host mount. Have not tested with WSL as guest since rust is globally broken there.

I have nothing related to git-credential-keepassxc under `%APPDATA%`.

**Comment by Frederick888** [comment]
What about configuring with `--config` from scratch then?

And `FOLDERID_RoamingAppData` = `%APPDATA%\Roaming` not `%APPDATA%`

**Comment by bendem** [comment]
`%APPDATA%`'s value is `%USERPROFILE%\AppData\Roaming`. Is the config format documented somewhere? What am I supposed to put in it?

**Comment by Frederick888** [comment]
@bendem I meant starting from scratch and carrying those 2 arguments all way along.

```sh
# bash syntax here, not sure about CMD/PowerShell, and I don't think WSL would work at all
$ git-credential-keepassxc -vvv --config /path/to/wherever/git-credential-keepassxc --socket '\\.\pipe\org.keepassxc.KeePassXC.BrowserServer' configure
$ printf 'url=https://example.com\n' | git-credential-keepassxc -vvv --config /path/to/wherever/git-credential-keepassxc --socket '\\.\pipe\org.keepassxc.KeePassXC.BrowserServer' get
```

**Comment by bendem** [comment]
Ah, I see the problem, I had refused to create the git group it asked for, and it's apparently a hard error that happens before saving the config. Really sorry about that, config system is working fine, just the path of the pipe is causing problems.

**Comment by Frederick888** [comment]
Thank you very much for all the feedback! Could you please try `issue-13` branch out to see if the default named pipe path problem is solved or not? You can either just checkout the branch and then `cargo build` or use `cargo install --git https://github.com/Frederick888/git-credential-keepassxc.git --branch issue-13`.
