### ISSUE TITLE
Named pipe moved again on windows

### ISSUE THREAD

**Issue by bendem** [Frederick888/git-credential-keepassxc#19]
Hello, the keepass named pipe moved again in the latest version, this time they added the username to it.

https://github.com/keepassxreboot/keepassxc/pull/5485/files

**Comment by Frederick888** [comment]
Could you please try the `win-pipe-path-2.6.2` branch out?

**Comment by bendem** [comment]
Sorry for the delay, wasn't at work. Yes, it works perfectly, thanks! ❤️
