### ISSUE TITLE
Another instance of KeePassXC is already running

### ISSUE THREAD

**Issue by ivankovnatsky** [Frederick888/git-credential-keepassxc#23]
first off thanks for the software!

i'm trying to configure it and perhaps i did something wrong on the way, if you could point where that would be really cool.

i did configure with: `git-credential-keepassxc configure`,

having this file:

```
{
  "databases": [
    {
      "id": "git-credential-keepassxc",
      "key": "xxx",
      "pkey": "xxx",
      "group": "Git",
      "group_uuid": "xxx"
    }
  ],
  "callers": [
    {
      "path": "/nix/store/j7cfd6hwir1hiqr9v774ng108py9x71q-zsh-5.8/bin/zsh",
      "uid": 1000,
      "gid": 100,
      "canonicalize": false
    }
  ]
}
```

keepassxc asked for a connection name, that went smoothly. it did create `Git` sub-directory in keepassxc. 

(do i need to configure my credentials manually or it should ask/save with prompts?)

from git config:

```
...
[credential]
        helper = "/nix/store/07f8mwjp8458nz28r03rdcp2jkwrpjli-keepassxc-2.6.4/bin/keepassxc"
...
```

(i'm having double thoughts about this, should not we be configuring `git-credentials-keepassxc` instead of the backend itself: `keepassxc` ?)

while running `git push` i'm getting:

```
QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
Another instance of KeePassXC is already running.
Username for 'https://github.com':
```

keepassxc configs:
![image](https://user-images.githubusercontent.com/75213/118763536-ae07bf00-b880-11eb-86c2-f96e894fa800.png)
![image](https://user-images.githubusercontent.com/75213/118763557-b4963680-b880-11eb-8896-8fc7629c930c.png)

Versions:
KeePassXC 2.6.4
git-credential-keepassxc 0.6.0
rustc 1.51.0
OS: NixOS

Compiled with notifications, encryption.

**Comment by Frederick888** [comment]
If you had followed [Readme](https://github.com/Frederick888/git-credential-keepassxc#configuration), the resulting `~/.gitconfig` would have been

```gitconfig
[credential]
        helper = keepassxc -v
```

instead what you've got currently.

Names of all Git credential helpers, of course including this project, start with `git-credential-`, and this prefix is omitted from `.gitconfig`.

For example, https://git-scm.com/docs/git-credential-cache (executable is `/usr/lib/git-core/git-credential-cache` under Arch):

> SYNOPSIS
>
> git config credential.helper 'cache [<options>]'

**Comment by Frederick888** [comment]
Or if you want to use absolute path, it should be the path to `git-credential-keepassxc` instead as you thought.
