### ISSUE TITLE
Is it possible to access "Additional Attributes" of an entry?

### ISSUE THREAD

**Issue by nifr** [Frederick888/git-credential-keepassxc#24]
Hi @Frederick888 ,
first of all THANK YOU so much for this awesome project. It really helps my daily work.

I have the following situation: 

I'd like to set an environment variable to a personal access token - `GITHUB_TOKEN` in this case - inside a script.
The token is stored inside my entry for github.com as an "Additional attribute" named `KPH: GITHUB_TOKEN`.

I have enabled the option `Return advanced string fields which start with "KPH: "` under `Settings -> Browser Integration`.
I was able to successfully deactivate the database entry by setting `KPH: git` to `false`. 

Sadly the additional entries specified by `KPH: *` are not returned by `git-credential-keepassxc`.
I am aware that I could duplicate the entries and use a different username.

Are the values filtered to `username`, `url` and `password` by the program?
Or is it possible to get access to these "Additional attributes" somehow?
That would be super awesome 😄 

```
printf "url=https://github.com\nusername=nifr\n" | git-credential-keepassxc get
```

output:

> username=nifr
> password=HIDDEN
> url=https://github.com

expected output:

> username=nifr
> password=HIDDEN
> url=https://github.com
> GITHUB_TOKEN=HIDDEN

Thanks in advance for your time and greetings from Cologne, Germany :)

**Comment by Frederick888** [comment]
You were right. `KPH: git` is the only field that `git-credential-keepassxc` processes. And actually these KPH fields are sent in a separate dictionary, which are not part of `git-credential-keepassxc` output in the first place.

Printing them out shouldn't be of too much hassle, but I'll probably need to provide an additional flag and think about what should happen if there are special characters in the field name.

In the meantime, unless you need both the password and the token, I'd suggest saving them in two different KeePass entries and then use `KPH: git` to disable the one with password.

**Comment by Frederick888** [comment]
Can you try the `--advanced-fields` flag on latest master branch?

**Comment by nifr** [comment]
Hey @Frederick888 👋 
Sorry for not getting back to you earlier this week.

I just had the chance to try out your updates on the `master` branch. 
You my friend are a coding machine ... and a magician! 😄 

All advanced fields prefixed with `KPH: ` are returned correctly if I use the `--advanced-fields` flag.

Thanks a million times. This is huge 🥰 

Could you tag a new release including the changes?

Also I'd be happy to donate you a coffee or or two for your efforts. How can I do so?

Greetings and have a nice weekend! 
Keep up the good work. Thank you so much.

**Comment by Frederick888** [comment]
Thanks for confirming.

> Could you tag a new release including the changes?

I'll update a few dependencies and release a new one later today.

> Also I'd be happy to donate you a coffee or or two for your efforts. How can I do so?

I really appreciate that. But for now I'd suggest you donate to https://keepassxc.org/donate/ or https://keepass.info/donate.html. This project wouldn't have existed without them after all :)
