### ISSUE TITLE
"--unlock" not working when Keepass is not running in english language

### ISSUE THREAD

**Issue by even-allmighty** [Frederick888/git-credential-keepassxc#26]
Hi, 

I found the unlock option not working for me.
I debugged until I found out, that my Keepass is returning a localized string when the database is locked.
This means the check in the following line fails:
https://github.com/Frederick888/git-credential-keepassxc/blob/d7909ab433597c99bf3d9cde63ecfe0b7d4abe49/src/keepassxc/errors.rs#L14

I just changed the string to the correct one and sure enough it started working.
Maybe there is a different way to check if the database is unlocked?

**Comment by Frederick888** [comment]
I probably should have used `errorCode` here: https://github.com/keepassxreboot/keepassxc/blob/0921bf2d61633531e20c45774eb9d24c153523eb/src/browser/BrowserAction.cpp#L38. I'll try it out.

**Comment by Frederick888** [comment]
Could you give the latest build a shot? Thanks

**Comment by even-allmighty** [comment]
Works. Thank you very much!
