### ISSUE TITLE
Release 0.8.2 flagged as Trojan by Microsoft Defender

### ISSUE THREAD

**Issue by fadnincx** [Frederick888/git-credential-keepassxc#27]
From the Release 0.8.2, the Windows files `windows-lastest-full.zip` and `windows-latest-minimal.zip` are blocked to download by Microsoft Defender because it detects `Trojan:Win32/spursint.Ficl`. I hope this is a false positive.

If so, digitally signing the executable probably helps to reduce the risk for such a event.

**Comment by Frederick888** [comment]
The binaries are built in [GH Actions](https://github.com/Frederick888/git-credential-keepassxc/actions/workflows/release.yml) and hashed, which is the best I can do at the moment. I've got no plan to purchase a certificate an sign them I'm afraid.

At the end of the day, if you don't trust the build process, you can build it yourself; if you don't trust the code, you'll have to go through it on your own.
