### ISSUE TITLE
How do I use this program?

### ISSUE THREAD

**Issue by NovaViper** [Frederick888/git-credential-keepassxc#28]
Hey, im trying to figure out how to use this program. I installed it from the [AUR repo](https://aur.archlinux.org/packages/git-credential-keepassxc) and a token password an entry within the additional attributes, but I can't figure out how to make the program read the extra attributes. I'm using ArchLinux with KeePassXC 2.6.6

I also get this error too
```
Nov 18 13:38:33.666 ERRO KeePassXC doesn't allow erasing logins via socket at the time of writing
remote: HTTP Basic: Access denied
remote: You must use a personal access token with 'read_repository' or 'write_repository' scope for Git over HTTP.
remote: You can generate one at https://gitlab.com/-/profile/personal_access_tokens
fatal: Authentication failed for 'https://gitlab.com/NovaViper/dotfiles.git/'
```

**Comment by Frederick888** [comment]
1. To make credentials directly available to Git without any middleman, save passwords in a different entry rather than advanced attributes
2. If you have to, `git-credential-keepassxc get -h`
3. A little gate keeping: Consider using SSH keys if possible

**Comment by NovaViper** [comment]
> 1. To make credentials directly available to Git without any middleman, save passwords in different entries rather than advanced attributes
> 
>     2. A little gate keeping: Consider using SSH keys if possible
> 
>     3. If you have to, `git-credential-keepassxc get -h`

I do have an ssh key for Gitlab but for some reason it never works, and I couldn't find anything online explaining how to use SSH keys with Gitlab, so I ended up having to create a 2FA key for it. And ah, I did manage to get the program to save the entries directly
