### ISSUE TITLE
More helpful message regarding caller failure 

### ISSUE THREAD

**Issue by stdedos** [Frederick888/git-credential-keepassxc#30]
I was wondering if you'd like to improve on the warning message given from the `git-credential-keepassxc`, when callers don't match.

I'd like to know who called me, so I can add (maybe?) them to the list.

**Comment by Frederick888** [comment]
Sure thing. I can change it to something like

> /path/to/program (uid=1, gid=1) is not allowed to call git-credential-keepassxc

If it's not too complicated, I can even print out the command that adds the caller I guess. Hope I can have some time to tackle this this weekend. There are also a few dependency upgrades that need to be taken care of.

**Comment by stavros-mobal** [comment]
Sounds awesome to me!

Add the aforementioned (basic) details in the next to replace the `N/A` string (if the `N/A` string "has a meaning" keep it; add the newline regardless).

More extensive details can be "hidden" under the `-v` (if it makes sense; I'll have to see the result before "making a ruling", should you be asking me)

Looking forward in using this feature; I am now "back" at the minimal version.
I also like the `notifications`, but caller is `mandatory` then; I don't want to build it myself 😓 

If you happen to have a `debian` directory, I have a pet project that can build this "automatically" in Docker.
Unless you have your own thing.

**Comment by stdedos** [comment]
Sounds awesome to me!

Add the aforementioned (basic) details in the next to replace the `N/A` string (if the `N/A` string "has a meaning" keep it; add the newline regardless).

It'd be a cute addition to add the necessary command to add the caller too.

Looking forward in using this feature; I am now "back" at the minimal version.
I also like the `notifications`, but caller is `mandatory` then; I don't want to build it myself 😓 

If you happen to have a `debian` directory, I have a pet project that can build this "automatically" in Docker.
Unless you have your own thing.

**Comment by stdedos** [comment]
PS: Are you "planning" on opening discussions?

I have more "generic" questions; but I don't want to open necessarily open an issue (and/or then have a "very nicely-cut issue topic"

**Comment by Frederick888** [comment]
> discussions

Enabled.

**Comment by stavros-mobal** [comment]
Thanks for merging the feature :-D

I hate to be the annoying one; but could you build a release? 😕 
I am not familiar with / I don't use the Rust toolchain, and I don't have it downloaded to try and build from sources.

**Comment by Frederick888** [comment]
You can download from [GHA](https://github.com/Frederick888/git-credential-keepassxc/actions/workflows/rust.yml) for now.

**Comment by stdedos** [comment]
Oh yeah - awesome :-D

**Comment by stdedos** [comment]
In Ubuntu "it seems necessary" to also add:
```
Feb 14 12:31:10.865 INFO Dump is disabled
Feb 14 12:31:10.865 INFO Reading configuration from /home/u/.config/git-credential-keepassxc
Feb 14 12:31:10.865 INFO PID: 284122
Feb 14 12:31:11.037 INFO PPID: 284121
Feb 14 12:31:11.038 INFO Parent process path: /usr/bin/dash
Feb 14 12:31:11.038 INFO Canonical parent process path: /usr/bin/dash
Feb 14 12:31:11.046 INFO Run `git-credential-keepassxc caller add --uid 1000 --gid 1000 /usr/bin/dash` to add current caller to allowed caller list
Feb 14 12:31:11.046 ERRO /usr/bin/dash (uid=1000, gid=1000) is not allowed to call git-credential-keepassxc, Caused by: N/A
```

ofc, that could very well avoided by changing user shells (?), but for _ages_ it's not the case (https://askubuntu.com/a/976487/645458, https://wiki.ubuntu.com/DashAsBinSh)

I can make a README.md PR if you'd agree with my analysis; or wherever you (want to) keep your FAQs
