### ISSUE TITLE
Prompt to use Yubikey?

### ISSUE THREAD

**Issue by stefan-matic** [Frederick888/git-credential-keepassxc#38]
Is it possible to implement a desktop notification to let the user know that it's waiting for the Yubikey Challenge-Response?

**Comment by Frederick888** [comment]
Is the `notification` feature [1][2] not what you want?

[1] https://github.com/Frederick888/git-credential-keepassxc#optional-features
[2] https://github.com/Frederick888/git-credential-keepassxc/blob/91346297b51893b1183409845df397decc26a247/src/config.rs#L806-L821

**Comment by stefan-matic** [comment]
Didn't notice that part of the code. but it seems the desktop notification don't work for me.

OS: KDE neon User - 5.24
Kernel: 5.15.35-xanmod1
DE: Plasma
Rust: rustc 1.58.1 (db9d1b20b 2022-01-20)

Let me double-check if I set everything right, I'll update after.

**Comment by stefan-matic** [comment]
It works with the full binary from releases. Seems something was wrong with my cargo installation.

Sorry for the false alarm!
