### ISSUE TITLE
`dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib` on macbook M1

### ISSUE THREAD

**Issue by muravjov** [Frederick888/git-credential-keepassxc#39]
I tried to use the latest release https://github.com/Frederick888/git-credential-keepassxc/releases/download/v0.9.1/macos-latest-full.zip
on my macbook  M1 (`arm64`) and got the link error
```
$ git-credential-keepassxc --help
dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/ilya/opt/opt/bin/git-credential-keepassxc
  Reason: image not found
Abort trap: 6
```

My env is:
```
$ uname -a
Darwin ilya-mbp.lan 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:38 PDT 2021; root:xnu-7195.141.8~1/RELEASE_ARM64_T8101 arm64 arm64 MacBookPro17,1 Darwin
```

Workaround: I installed the tool from sources with rustup and it works perfectly. Thanks!

**Comment by Frederick888** [comment]
AFAIK there are no free GitHub-hosted M1 action runners available atm.
