### ISSUE TITLE
KeePassXC update 2.7.2/2.7.3 breaks connection to Unix socket

### ISSUE THREAD

**Issue by stefan-matic** [Frederick888/git-credential-keepassxc#53]
Hello,

I've updated to 2.7.3 and I've experience the following issue when trying to configure git-credential-keepassxc:

```
Oct 26 12:56:57.463 ERRO Failed to connect to Unix socket /run/user/1000/org.keepassxc.KeePassXC.BrowserServer, Caused by: Connection refused (os error 111)
```
It might be related to the recent change in KeePassXC issue [#8030](https://github.com/keepassxreboot/keepassxc/pull/8030) which was merged into 2.7.2 and 2.7.3

Once I revert KeePassXC to 2.7.1 the git-credential-keepassxc is able to communicate with it.

**Comment by Frederick888** [comment]
Hopefully I can have some time to tackle this over the weekend. For now there's `--socket`.
