### ISSUE TITLE
Notifications configurable via config file

### ISSUE THREAD

**Issue by diggit** [Frederick888/git-credential-keepassxc#59]
Hi,
is it possible to disable notification via config file or do I have to rebuild with notification feature disabled?
Rebuilding is a bit inconvenient for SW installed using package manager...

**Comment by Frederick888** [comment]
I suggest you do this using your DE/WM's configurations. Per-application built-in notification switches are mostly unnecessary and obsolete these days imo (unless you're building a browser or something).

**Comment by diggit** [comment]
I have ligtweight desktop with just dunst as notifier. I'll give it a try ty solve on the other end. Thanks!
